# Generated by Django 5.0.2 on 2024-04-17 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("links", "0002_alter_link_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="favicon",
            field=models.URLField(blank=True, null=True),
        ),
    ]
